services:
  obj-det:
    container_name: my-obj-det 
    image: alirezafazli29/obj-det:dev
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8001:8080"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all